---
title: "UCR proyecto final"
author: "Jose Pablo Gómez Mata"
date: "7/19/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r}
library(readxl)
library(tidyverse)
library(cluster)
library(vegan)
suppressMessages(library(caret))
suppressMessages(library(DT))
suppressMessages(library(ROCR))
suppressMessages(library(class))
suppressMessages(library(kknn))
suppressMessages(library(e1071))
suppressMessages(library(plotly))
suppressMessages(library(adabag))
suppressMessages(library(randomForest))
library(modeest)
library(ISLR)
library(arules)
library(cluster)
library(neuralnet)
library(shipunov)
library(StatMatch)
library(rattle)
library(modeest)
library(pROC)
```

# Base
```{r}
ucr <- read.csv("ucr.csv")
ucr$colegio <- factor(ucr$colegio)
ucr$provincia <- factor(ucr$provincia)
ucr$canton <- factor(ucr$canton)
ucr$distrito <- factor(ucr$distrito)
ucr$tipo_colegio <- factor(ucr$tipo_colegio)
ucr$tipo_horario <- factor(ucr$tipo_horario)
ucr$tipo_modalidad <- factor(ucr$tipo_modalidad)
ucr$codigo_zona_procedencia <- factor(ucr$codigo_zona_procedencia)
ucr$rama1_mep <- factor(ucr$rama1_mep)
ucr$in0vacion_mep <- factor(ucr$in0vacion_mep)
ucr$v_agregado_mep <- factor(ucr$v_agregado_mep)
ucr$ambiental_mep <- factor(ucr$ambiental_mep)
ucr$o_tecnolog_mep <- factor(ucr$o_tecnolog_mep)
ucr$modeloiiicicloydiversificado_mep <- factor(ucr$modeloiiicicloydiversificado_mep)
ucr$deportivo_mep <- factor(ucr$deportivo_mep)
ucr$telesecundaria_mep <- factor(ucr$telesecundaria_mep)
ucr$liceo_rural_mep <- factor(ucr$liceo_rural_mep)
ucr$tipo_educa <- factor(ucr$tipo_educa)
ucr$indigena_mep <- factor(ucr$indigena_mep)
ucr$territorio_indig_mep <- factor(ucr$territorio_indig_mep)
ucr$lengua_indig_mep <- factor(ucr$lengua_indig_mep)
ucr$bilingue_mep <- factor(ucr$bilingue_mep)
ucr$bach_internacional_mep <- factor(ucr$bach_internacional_mep)
ucr$admitido <- factor(ucr$admitido)
levels(ucr$admitido) <- c("admitido","no admitido")
ucr <- ucr[,-c(1:4)]
str(ucr)

# train y test

RNGkind(sample.kind = "Rounding")
set.seed(10)

n=nrow(ucr)
s=sample(1:n,round(0.8*n))
train=ucr[s,]
test=ucr[-s,]

```

#funciones
```{r}
# Funcion para generar el grafico y calculo de AUC
curvaROC = function(pred,y, grafico = F) {
  predict = prediction(pred,y) 
  auc = attributes(performance(predict,"auc"))$y.values[[1]]*100
  des = performance(predict,"tpr","fpr")
  p = NULL
  if(grafico){
    FP = attributes(des)$x.values[[1]]*100
    PP = attributes(des)$y.values[[1]]*100
    p <- plot_ly(x = FP, y = FP, name = 'Línea No Discrimina', 
                 type = 'scatter', mode = 'lines',
                 line = list(color = 'rgba(0, 0, 0, 1)', 
                             width = 4, dash = 'dot'),
                 fill = 'tozeroy',  fillcolor = 'rgba(0, 0, 0, 0)') %>% 
      add_trace(y = PP, name = paste('Curva ROC (AUC = ', round(auc,3),')', sep =""), 
                line = list(color = 'rgba(0, 0, 255, 1)', width = 4, 
                dash = 'line'),  fillcolor = 'rgba(0, 0, 255, 0.2)')%>%
      layout(title = "Curva ROC",
             xaxis = list(title = "<b>Falsos Positivos (%)<b>"),
             yaxis = list (title = "<b>Precisión Positiva (%)<b>"))
  }
  return(list(auc = auc,grafico = p))
}

# eval
eval = function(y,pred){
  confu=table(y,pred)
  e = 1-sum(diag(confu))/sum(confu)
  falsos = 1-diag(confu)/apply(confu, 1, sum)
  error = c(e,falsos)*100
  roc_object <- roc(y, as.numeric(pred))
  auc <- auc(roc_object)[1]
  indicadores = c(error,auc)
  names(indicadores)=c("e","FP","FN","AUC")
  return(list(Matriz=confu,indicadores=indicadores))
  
}

# knn con dist de gower
knngow <- function (train,test,k) 
  {#require(StatMatch)
 p=dim(train)[2]
 ntest=dim(test)[1]
 ntrain=dim(train)[1]
 classes=rep(0,ntest)
 if(ntest==ntrain)
{     for(i in 1:ntest)
     { tempo=order(gower.dist(test[i,-p],train[-i,-p]))[1:k]
       classes[i]=mlv(train[tempo,p])[1]}
 }
     else{
  for(i in 1:ntest)
{ tempo=order(StatMatch::gower.dist(test[i,-p],train[,-p]))[1:k] 
classes[i]=mlv(train[tempo,p])[1]}
}
classes
}
```


# modelos
```{r}
# arbol:
mod_arbol = rpart(admitido ~ ., method="class", data=train,
                  control = rpart.control(minsplit = 326,minbucket = 163,cp = 0.0005, maxdepth = 7))

fancyRpartPlot(mod_arbol , palettes=c("Greens", "Reds"))
# plot(mod_arbol)
pred1=predict(mod_arbol,newdata = test, type = "class")

table(test$admitido,pred1)

# bagging
library(adabag)

mod_bagg=bagging(admitido~., method="class", 
                 control = rpart.control(minsplit = 326,minbucket = 163,cp = 0.0005, maxdepth = 7),
                 data = ucr, mfinal = 19)


pred_bagg = predict(mod_bagg,ucr)$class

table(ucr$admitido,pred_bagg)


# random forest

library(randomForest)

mod_RF = randomForest(admitido~.,method="class",data = train, ntree=99) # numero impar por el empate en dentro de los arboles
pred_RF = predict(mod_RF, test)

table(test$admitido,pred_RF)


# boosting
library(adabag)

mod_boos <- boosting(admitido~.,data = train, boos = T, mfinal = 5)
pred_boos <- predict(mod_boos,test) #me da prob
clase_boo <- pred_boos$class #Aca me da clase

table(test$admitido,clase_boo)

# logisticos

mod_log = glm(factor(admitido)~.,data = train,family = binomial)

pre_log = predict(mod_log,newdata = test, type = "response")>0.5

table(test$admitido,pre_log)

# knn
mod_knn <- knngow(train = train, test = test, k = 5)

table(test$admitido,mod_knn)
```

# validacion cruzada

```{r}
# --------------------------------------------------------------------------- validación cruzada
cortes=createFolds(1:nrow(ucr),k=10) # con 10 cortes
res2 = matrix(nrow = 10, ncol = 4)
colnames(res2) = c("e","FP","FN","AUC")

# ------------------------------------------------ modelo logistico:

for(i in 1:10){
  train3 = ucr[-cortes[[i]],]
  test3 = ucr[cortes[[i]],]
  mod_log = glm(factor(admitido)~.,data = train,family = binomial)
  pre_log = predict(mod_log,newdata = test3, type = "response")>0.5
  f5=eval(test3$admitido, as.numeric(pre_log))
  res2[i,] = f5$indicadores
}

# ------------------------------------------------ para un arbol de desicion:
# para el arbol (ajustar cp)
res_cp = matrix(nrow = 10, ncol = 4)
colnames(res_arb) = c("e","FP","FN","AUC")
res_abr <- list()
itera <- seq(from = 0.00001, to = 0.05, length.out = 20)

for (j in 1:length(itera)) {
  for(i in 1:10){
    train3 = ucr[-cortes[[i]],]
    test3 = ucr[cortes[[i]],]
    mod_arbol = rpart(admitido ~ ., method="class", data=train3,
                  control = rpart.control(minsplit = 326,minbucket = 163,cp = itera[j]))
    pred1=predict(mod_arbol,newdata = test3, type = "class")
    f5=eval(test3$admitido, as.numeric(pred1))
    res_cp[i,] = f5$indicadores
    
  }
  res_abr[[j]] <- res_cp
}

medias_arb <- matrix(NA, nrow = length(itera), ncol = 4)


for (i in 1:20) {
    medias_arb[i,] <- apply(res_abr[[i]], 2, mean)
  }


rownames(medias_arb) <- round(itera,6)
colnames(medias_arb) <- c("e","FP","FN","AUC")

AUC_tot <-cbind(res_abr[[3]][,4],res_abr[[4]][,4],res_abr[[5]][,4])
colnames(AUC_tot) <- c("cp: 0.005","cp: 0.0078","cp: 0.01")

matplot(AUC_tot, type = "l", lty = 1, ylim = c(0.48,0.53), ylab = "AUC", xlab = "Repetición")
legend("topright", colnames(AUC_tot), col = 1:3, lty = 1, bty = "n")
medias=apply(AUC_tot, 2, mean)
abline(h=medias, col=1:3,lty= 2)

# para ajustar maxdepth:
res_depth = matrix(nrow = 10, ncol = 4)
colnames(res_depth) = c("e","FP","FN","AUC")
res_abr2 <- list()
itera <- seq(1,15)

for (j in 1:length(itera)) {
  for(i in 1:10){
    train3 = ucr[-cortes[[i]],]
    test3 = ucr[cortes[[i]],]
  
 
    mod_arbol = rpart(admitido ~ ., method="class", data=train3,
                  control = rpart.control(minsplit = 326,minbucket = 163,cp = 0.005, maxdepth = itera[i]))
  
    pred1=predict(mod_arbol,newdata = test3, type = "class")
    f5=eval(test3$admitido, as.numeric(pred1))
    res_depth[i,] = f5$indicadores
    
  }
  res_abr2[[j]] <- res_depth
}


medias_arb2 <- matrix(NA, nrow = length(itera), ncol = 4)
for (i in 1:15) {
  
  medias_arb2[i,] <- apply(res_abr2[[i]], 2, mean)
  
}

matplot(medias_arb2[,4], type = "l", lty = 1, ylim = c(0.48,0.53), ylab = "AUC", xlab = "Repetición")
legend("topright", "AUC", col = 1:3, lty = 1, bty = "n")
medias=apply(medias_arb2[,4], 2, mean)
abline(h=medias, col=1:3,lty= 2)

# utilizamos un arbol con 0.005 de cp y maxdepth de 7

# -------------------------------------------------------------------- para el BAGGING

res_bagg = matrix(nrow = 10, ncol = 4)
colnames(res_bagg) = c("e","FP","FN","AUC")
bagg <- list()
mfinal <- seq(11,21, by = 2)

for (j in 1:length(itera)) {
  for(i in 1:10){
    train3 = ucr[-cortes[[i]],]
    test3 = ucr[cortes[[i]],]
  
    mod_bagg=bagging(admitido~., method="class", 
                 control = rpart.control(minsplit = 326,minbucket = 163,cp = 0.005, maxdepth = 7),
                 data = train3, mfinal = mfinal[j])
    pred_bagg = predict(mod_bagg,test3)$class
  
    f5=eval(test3$admitido, as.numeric(factor(pred_bagg)))
    res_bagg[i,] = f5$indicadores
  }
  bagg[[j]] <- res_bagg
}

bagg

```































